fx_version 'adamant'

author 'Project Sloth'

discord 'https://discord.gg/projectsloth'

game 'gta5'

version '1.0'

data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_rsaltedcaramel.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_salted.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_strawberry.ytyp'
