fx_version 'adamant'

author 'Project Sloth'

discord 'https://discord.gg/projectsloth'

game 'gta5'

version '1.0'

data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_rsaltedcaramel.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_salted.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_awrootbeer.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_cherrycoke.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_coke.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_dietdew.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_dppepper.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantagrape.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantaorange.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantapineapple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_mountaindew.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_redbull.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_redbullsugarfree.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_sprite.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_blueberry_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_bubblegum_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cheesecake_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherry_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cola_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_doubleapple_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_elfbull_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_grape_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_greenapple_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_mango_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_strawberryice_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_watermelon_elfbar.ytyp'