fx_version 'adamant'

author 'Project Sloth'

discord 'https://discord.gg/projectsloth'

game 'gta5'

version '1.3'

data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_rsaltedcaramel.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_shake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_bubblegum.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_cherry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_chocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_doublechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_frappe.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_lemon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_mint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_raspberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_salted.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherryshake_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_awrootbeer.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_cherrycoke.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_coke.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_dietdew.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_dppepper.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantagrape.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantaorange.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_fantapineapple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_mountaindew.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_redbull.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_redbullsugarfree.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_can_sprite.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_blueberry_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_bubblegum_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cheesecake_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cherry_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_cola_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_doubleapple_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_elfbull_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_grape_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_greenapple_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_mango_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_strawberryice_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_watermelon_elfbar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_blueraspberrry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_grape.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_icepop.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_lemonlime.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_metamoon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_orange.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_prime_tropicalpunch.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_slothbucks.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_starbuckscan_coffeeshot.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_starbuckscan_hazelnut.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_starbuckscan_mocha.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_starbuckscan_vanilla.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_starbuckscan_whitechocolate.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_black.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_blue.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_cream.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_green.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_grey.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_purple.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_purpleweed.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_red.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/brum_jetlighter_white.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ps_jarrito_grapefruit.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ps_jarrito_lime.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ps_jarrito_mandarin.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ps_jarrito_strawberry.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ps_jarritos_mango.ytyp'
